version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: portfolio-frontend
    ports:
      - '${VITE_PORT_HOST}:${VITE_PORT}'
    restart: unless-stopped