name: Deploy to Docker Server
run-name: "🚀 Deploy: ${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}

      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          source: "."
          target: ${{ secrets.SERVER_PATH }}
          overwrite: true

      - name: SSH to server and rebuild Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            docker compose down
            docker compose build --no-cache
            docker compose up -d
