name: Deploy to Docker Server
run-name: "🚀 Deploy: ${{ github.event.head_commit.message || 'Manual run' }}"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Запускаем ssh-agent и добавляем ключ с паролем
      - name: Start SSH agent and add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}

      # 3️⃣ Копируем код на сервер
      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          source: "."
          target: ${{ secrets.SERVER_PATH }}
          overwrite: true

      # 4️⃣ Выполняем команды на сервере: пересобираем Docker
      - name: SSH to server and rebuild Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            echo "Stopping containers..."
            docker compose down || true
            echo "Rebuilding images..."
            docker compose build --no-cache
            echo "Starting containers..."
            docker compose up -d
            echo "✅ Deploy complete!"
